#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &
$HOME/.config/polybar/launch.sh
nitrogen --restore &

bspc monitor -d      
bspc config border_width         2
bspc config window_gap          10

bspc config split_ratio          0.5
bspc config borderless_monocle   true
bspc config gapless_monocle      false

bspc config focus_follows_pointer true

bspc rule -a Firefox desktop='^1'
#bspc rule -a TelegramDesktop state=floating follow=off desktop='^1'
bspc rule -a TelegramDesktop state=floating follow=off rectangle=900x600+510+240
bspc rule -a Lutris state=floating follow=off rectangle=1200x700+360+190 desktop='^6' 
bspc rule -a mpv state=floating rectangle=800x450+560+315 follow=off
bspc rule -a Inkscape desktop='^3'
bspc rule -a Blender desktop='^2'
